import json
import requests

# Simulate the same patient case from the form
payload = {
    'patientName': 'faraz',
    'age': 56,
    'sex': 'male',
    'symptomsText': 'chest pain',
    'durationHours': 1,
    'vitals': {
        'heartRate': 112,
        'systolicBP': 56,
        'diastolicBP': 78,
        'spo2': 89,
        'temperatureC': 39
    }
}

resp = requests.post('http://localhost:8000/api/triage', json=payload)
data = resp.json()

print('=' * 80)
print('ANALYSIS: WHICH PARTS ARE FROM OPENAI LLM')
print('=' * 80)
print()

print('1. FIRST AID RECOMMENDATIONS')
print('   Status: Generated by llm_service.generate_case_report()')
print('   Source: OpenAI ChatGPT API Call')
print('   Content:')
for aid in data['final']['report']['recommendations']['firstAid']:
    print(f'     • {aid}')
print()

print('2. SEVERITY ASSESSMENT')
print('   Status: Rule-Based (NOT from LLM)')
print('   Source: severity_prediction_agent() in agents.py')
print(f'   Severity Band: {data["final"]["report"]["triage"]["severityBand"].upper()}')
print(f'   Risk Score: {data["final"]["report"]["triage"]["riskScore"]} (calculated from vitals)')
print()

print('3. SPECIALIST RECOMMENDATIONS')
print('   Status: Rule-Based (NOT from LLM)')
print('   Source: doctor_recommendation_agent() in agents.py')
specs = data['final']['report']['recommendations']['suggestedSpecialties']
print(f'   Specialties: {", ".join(specs)}')
print('   Logic: Symptoms "chest pain" + SpO2 < 92 --> triggers Cardiology + Pulmonology')
print()

print('4. PRIORITY CLASSIFICATION')
print('   Status: Rule-Based (NOT from LLM)')
print('   Source: emergency_priority_classifier() in agents.py')
print(f'   Priority: {data["final"]["report"]["triage"]["emergencyPriority"]}')
print('   Logic: Severity=CRITICAL --> P1 (EMERGENCY)')
print()

print('5. COMMUNITY RESOURCE PLANNING')
print('   Status: Rule-Based (NOT from LLM)')
print('   Source: community_response_coordinator() in agents.py')
print('   Plan: Dispatch Ambulance A1, Route to Hospital H1')
print('   Logic: P1 priority --> immediate ambulance dispatch + hospital routing')
print()

print('6. SEVERITY DRIVERS')
print('   Status: Rule-Based (NOT from LLM)')
print('   Source: severity_prediction_agent() in agents.py')
print('   Content:')
for driver in data['final']['report']['rationale']['severityDrivers']:
    print(f'     • {driver}')
print()

print('=' * 80)
print('SUMMARY: WHAT IS FROM OPENAI LLM?')
print('=' * 80)
print()
print('✅ FROM OPENAI LLM:')
print('   └─ FIRST AID RECOMMENDATIONS (personalized medical guidance)')
print()
print('❌ NOT FROM OPENAI LLM (Rule-Based):')
print('   ├─ Severity Assessment (CRITICAL, Risk Score 21)')
print('   ├─ Specialist Recommendations (Cardiology, Pulmonology)')
print('   ├─ Priority Classification (P1 - EMERGENCY)')
print('   ├─ Community Resource Allocation (Ambulance dispatch)')
print('   └─ Severity Drivers (Low SpO2, Chest pain, Low BP)')
print()
